[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cognax"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "numpyro",
    "tensorflow-probability",
    "numpy",
]


# [tool.setuptools]
# packages = ["cognax"]