[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cognax"

# This is set automatically by flit using `penzai.__version__`
dynamic = ["version"]
description = "Build, fit, and sample from cognitive models with JAX + NumPyro."
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [{ name = "Ami Falk", email = "aaf2pz@virginia.edu" }]
keywords = ["cognitive-science", "modeling-tools", "jax", "numpyro"]
urls = { repository = "https://github.com/compmem/cognax/" }
dependencies = ["numpyro >= 0.21", "numpy"]
# pandas is a dependency for df_util.py

[project.optional-dependencies]
examples = ["arviz", "jupyter", "matplotlib"]

[dependency-groups]
dev = ["pytest", "ruff"]
